---
- hosts: all
  tasks:
    - package:
        name: nginx
        state: present
    - copy:
        src: /home/petko/playbooks/index.html
        dest: /usr/share/nginx/html/index.html
    - service:
        name: nginx
        state: started